jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '24' # <- add this

      - uses: actions/setup-node@v4
        with:
          node-version: '24' # <- add this
          cache: 'npm'

      - run: npm ci
      - run: npm run build
